### PR TITLE
Add FR translations

### PR DESCRIPTION
**Pull request by TotomInc**
Thanks for the plugin, I've added french translations for your plugin. 🙂

### CODE REVIEW

**Comment by mattmilburn** [comment]
@TotomInc Thank you for contributing the French translation! 👏🏻 

I just merged an important update into `staging` that features **minor changes** to the translations. Do you mind referencing this updated English file to modify your PR? I'll happily merge this into `staging` and put together the next release after that 👍🏻 

The diff for the `en.json` updates [can be found here](https://github.com/mattmilburn/strapi-plugin-menus/pull/27/files#diff-99a23c21f1c3d148980f67693f7bf7bde4069cfe397fb90f778fdabf8556c7e4).

**Comment by mattmilburn** [comment]
And forgive me because I'm using Google Translate to double-check translations. It looks like there is just one discrepancy in the verbiage for `ui.deleted.menu`.

Your translation translates to **The menu item has been removed**.

> It should be **menu** and not **menu item**.

Should the correct French translation be **Le menu a été supprimé**?

**Comment by TotomInc** [comment]
Thanks for your feedback.

> Should the correct French translation be Le menu a été supprimé?

Yes, you are right. It's a small error from my part. I'll fix this and update the translation file by updating the branch.

**Comment by TotomInc** [comment]
@mattmilburn I've pushed my latest changes by merging your updates from the `staging` branch.

Translation file is updated and has the new i18n strings, the invalid wording for `ui.deleted.menu` has been fixed.

Please, let me know if there is something else invalid/missing! 🙂

**Comment by mattmilburn** [comment]
@TotomInc Excellent. Thank you!

**Pull request merged**
